[project]
name = "ai-agent-evaluator"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["bird-feeder", "tqdm>=4,<5"]

[tool.uv.sources]
agent = { workspace = true }
scaffold = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]


[tool.pyright]
typeCheckingMode = "strict"
