[package]
name = "agent-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version="^1.0.219", features=["derive"] }
chrono = { version="^0.4.41", features=["serde"] }
serde_json = "1.0.140"
