name: Cargo Clippy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo clippy
        working-directory: evaluator
        run: cargo clippy -- -D warnings